# Generated by Django 5.0.4 on 2024-04-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelae_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='candle',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candelae_app.story'),
        ),
        migrations.AddField(
            model_name='candle',
            name='ingredients',
            field=models.ManyToManyField(default=None, related_name='candles', to='candelae_app.ingredient'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_types',
            field=models.ManyToManyField(default=None, related_name='stories', to='candelae_app.storytype'),
        ),
    ]
