# Generated by Django 5.0.4 on 2024-04-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candelae_app', '0002_ingredient_storytype_candle_story_candle_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candle',
            table='candle',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='story',
            table='story',
        ),
        migrations.AlterModelTable(
            name='storytype',
            table='story_type',
        ),
    ]
