# Generated by Django 5.0.4 on 2024-04-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candelae_app', '0003_alter_candle_table_alter_ingredient_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['name'], 'verbose_name': 'Свеча', 'verbose_name_plural': 'Свечи'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['description'], 'verbose_name': 'Сюжет', 'verbose_name_plural': 'Сюжеты'},
        ),
        migrations.AlterModelOptions(
            name='storytype',
            options={'ordering': ['name'], 'verbose_name': 'Тип сюжета', 'verbose_name_plural': 'Типы сюжетов'},
        ),
        migrations.AddField(
            model_name='story',
            name='short_story_name',
            field=models.CharField(default='Краткое имя сюжета', max_length=30, verbose_name='Сюжет'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='description',
            field=models.TextField(verbose_name='Описание свечи'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='ingredients',
            field=models.ManyToManyField(default=None, related_name='candles', to='candelae_app.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название свечи'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candelae_app.story', verbose_name='Сюжет'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(verbose_name='Описание сюжета'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_types',
            field=models.ManyToManyField(default=None, related_name='stories', to='candelae_app.storytype', verbose_name='Типы сюжета'),
        ),
        migrations.AlterField(
            model_name='storytype',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Тип сюжета'),
        ),
    ]
