services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: paul_admin
      POSTGRES_DB: candelae_main
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./configurations/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  web:
    container_name: wsgi_app
    build:
      context: configurations/python-deps
    ports:
      - 8000:81
    networks:
      main:
        aliases:
          - web-net


  nginx:
    build:
      context: configurations/nginx
    container_name: nginxFront
#    links:
#      - web:web
    depends_on:
      - web
    ports:
      - 8080:81 # map: host -> docker, 81 because port 80 is for default conf.d
    volumes:
      - ./webserver_static_files/public:/etc/nginx/public # shared memory map: my_path:docker_unix_path
    networks:
      main:
        aliases:
          - nginx-net

networks:
  main: