services:
  django-app:
    build:
      context: candelae
    ports:
      - 9999:9999
    depends_on:
      - db
      - nginx
    networks:
      main:
        aliases:
          - django-net


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: paul_admin
      POSTGRES_DB: candelae_main_docker
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./candelae/configs/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - db

  web:
    container_name: wsgi_app
    build:
      context: candelae/configs/wsgi
    ports:
      - 8000:81
    networks:
      main:
        aliases:
          - web-net


  nginx:
    build:
      context: candelae/configs/nginx
    container_name: nginxFront
#    links:
#      - web:web
    depends_on:
      - web
    ports:
      - 8080:81 # map: host -> docker, 81 because port 80 is for default conf.d
    volumes:
      - ./webserver_static_files/public:/etc/nginx/public # shared memory map: my_path:docker_unix_path
    networks:
      main:
        aliases:
          - nginx-net

networks:
  db:
    driver: bridge
  main:
